<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <title>Sales Report</title>
  <style type="text/css">
    @page {
      size: A3;
      margin: 1cm;
    }

    .table {
      width: 100%;
      max-width: 100%;
      background-color: #fff;
    }

    .table th,
    .table td {
      padding: 1px;
    }

    .table thead th {
      border-bottom: 1px solid #000;
    }

    .table tbody+tbody {
      border-top: 1px solid #000;
    }

    .table .table {
      background-color: #fff;
    }

    .list-group {
      display: block;
      width: 100%;
      list-style: none;
      margin-top: 15px;
      margin-bottom: 15px;
    }

    .list-group p {
      width: 100%;
      height: 20px;
      line-height: 20px;
      list-style: none;
      font-size: 1.1em;
    }
  </style>
</head>

<body>

  <div class="container">
    <div class="card">
      <div class="card-header">
        <center>
          <h1>Sales Report </h1>( Leminates Sales List )
        </center>
      </div>

      <div class="list-group">
        <p>Generated By: {{ $name }}</p>
        <p>From Date: {{ $f_date }} &nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;To Date: {{ $t_date }}</p>
      </div>
      @if ($sales->count() > 0)
      <table class="table">
        <thead>
          <tr>
            <th>No</th>
            <th>Product</th>
            <th>Address</th>
            <th>Date</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Status</th>
            <th>Customer</th>
            <th>Supplier</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($sales as $sales)
          <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{$sales->p_name}}</td>
            <td>{{$sales->s_o_address}}</td>
            <td>{{$sales->s_o_date}}</td>
            <td>{{$sales->s_o_d_quantity}}</td>
            <td>{{$sales->s_o_d_total}}</td>
            <td>{{$sales->s_o_status}}</td>
            <td>{{$sales->u_name}}</td>
            <td>{{$sales->s_name}}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
      @endif
    </div>
  </div>

</body>

</html>