<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <title>Sales Report</title>
  <style type="text/css">
    @page {
      size: A3;
      margin: 1cm;
    }

    .table {
      width: 100%;
      max-width: 100%;
      background-color: #fff;
    }

    .table th,
    .table td {
      padding: 1px;
    }

    .table thead th {
      border-bottom: 1px solid #000;
    }

    .table tbody+tbody {
      border-top: 1px solid #000;
    }

    .table .table {
      background-color: #fff;
    }

    .list-group {
      display: block;
      width: 100%;
      list-style: none;
      margin-top: 15px;
      margin-bottom: 15px;
    }

    .list-group p {
      width: 100%;
      height: 20px;
      line-height: 20px;
      list-style: none;
      font-size: 1.1em;
    }
  </style>
</head>

<body>

  <div class="container">
    <div class="card">
      <div class="card-header">
        <center>
          <h1>Customers Report </h1>( Leminates registered Customer List )
        </center>
      </div>

      <div class="list-group">
        <p>Generated By: {{ $name }}</p>
        <p>Date: {{ $today }}</p>
      </div>

      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Email</th>
            <th>Birth date</th>
            <th>Address</th>
            <th>Contact</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
          <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->dob }}</td>
            <td>{{ $user->address }}</td>
            <td>{{ $user->m_no }}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>

</body>

</html>